# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=500, verbose_name='密码')),
                ('image', models.CharField(max_length=255, verbose_name='头像')),
                ('add_time', models.DateTimeField(verbose_name='注册时间')),
                ('last_time', models.DateTimeField(verbose_name='最近登录时间')),
                ('phone_type', models.CharField(max_length=30, verbose_name='登录平台，安卓或iOS')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
